services:
  database:
    container_name: horo-database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    container_name: horo-php
    build:
      context: .
      dockerfile: ./php/Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www
      - ./vendor:/var/www/vendor
    depends_on:
      - database
  nginx:
    container_name: horo-nginx
    image: nginx:stable-alpine
    ports:
      - '8082:82'
    volumes:
      - ./public:/var/www/public
      - ./nginx/nginx-default.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - database